<?php

$labels = array();
$labels['export_provisioning'] = 'Download Mail Configuration';
$labels['pagetitle'] = 'Export Email Profile';
$labels['boxtitle'] = 'Export Email Configuration Profile';
$labels['apple'] = 'Apple';
$labels['microsoft'] = 'Microsoft';
$labels['download_ios'] = 'Download provisioning (configuration) profile for iOS / OSX';
$labels['download_iaf'] = 'Download provisioning (configuration) profile for Outlook Express / Windows Live Mail';
$labels['PayloadDescription'] = 'email account settings'; // description inside configuration profile
$labels['identity'] = 'Email Account Title';



?>
